import express from 'express';
import upload from './upload/upload';
import product from './products/products';
import news from './news/News';
import users from './users/users';
import question from './question/controllerQuestion';
const router = express.Router();
router.use("/upload",upload);
router.use("/product",product);
router.use("/news",news);
router.use("/user",users);
router.use("/question",question);
export default router ;